РК1 DONE
frontend-park-mail-ru/2024_2_ThereWilIBeName pull request #9
Opened 2024-10-29 09:21 UTC by SLDminor

2024-10-30 00:05 UTC, SergTyapkin requested changes

2024-10-30 16:36 UTC, SLDminor commented on index.html
> +    <div class="" id="root"></div>
Потому что теперь я меняю стили через class, а не через ссылку на css файл

2024-10-30 16:46 UTC, SergTyapkin commented on index.html
> +    <div class="" id="root"></div>
Но писать в html атрибут class вообще без пояснений - это тоже странно. Либо с пояснениями, либо никак не надо. Это только путает

2024-10-30 17:07 UTC, SLDminor commented on eslint.config.mjs
> +        ignores: ['server/*', 'webpack.config.js', 'build/*'],
Потому что мне нужно там использовать то, на что линтер ругается

2024-10-30 17:46 UTC, SergTyapkin commented on eslint.config.mjs
> +        ignores: ['server/*', 'webpack.config.js', 'build/*'],
А, я забыл, что он в среде node запускается)
Тогда да, нормально

2024-10-30 18:10 UTC, SLDminor commented on src/styles/gallery.styl
> +.home-page
Потому что цвета подтягиваются в index.styl

2024-10-31 14:13 UTC, SLDminor commented on src/styles/gallery.styl
> +        filter drop-shadow(-16px 16px 0px my-shadow)
Он квадратную тень отбрасывает

2024-10-31 14:13 UTC, SLDminor commented on src/styles/gallery.styl
> +        margin 0
Почему?

2024-10-31 14:13 UTC, SLDminor commented on src/utils/Api.ts
> +    created_at: string,
на бэке так

2024-10-31 21:18 UTC, merged